(()=>{'use strict';
const data=window.ATLAS_DATA,domains=data.domains,systems=domains.flatMap(d=>d.systems),$=s=>document.querySelector(s),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let domain=null,currentSystem=null,selected=new Set(),step=0,read=new Set(),origin=null,boxMode=false,storageOK=true;
try{const a=JSON.parse(localStorage.getItem('dabin-atlas-v22')||'[]');if(Array.isArray(a))read=new Set(a.filter(id=>systems.some(s=>s.id===id)))}catch{storageOK=false}
const frames=[0,5,7,2,3,15,6,1,4,11,10,9,14],rows=[[38,390],[395,720],[735,1055],[1060,1380]];
function portrait(s){const id=frames[s.npcModel-1],r=Math.floor(id/4),c=id%4;return `<span class="atlas-portrait" style="--x:${c*272};--y:${rows[r][0]};--h:${rows[r][1]-rows[r][0]}" aria-hidden="true"></span>`}
$('.cosmos').insertAdjacentHTML('beforeend',`<div class="atlas-hud"><header class="atlas-heading"><span>THE BUSINESS ATLAS / 业务探索地图</span><h2 id="atlas-title">五大洲，一个自动化世界。</h2><p id="atlas-subtitle">4 个业务域 · 13 套系统 · 42 个子模块</p></header><nav class="atlas-toolbar" aria-label="视角导航"><button id="atlas-back" hidden>← 五大洲总览</button><button id="atlas-turn" aria-label="绕星球向右旋转90度">旋转 90° ↻</button><button id="atlas-box" aria-pressed="false">框选大洲</button><button id="atlas-catalog">系统图鉴 <b>0 / 13</b></button></nav><aside class="atlas-aside" aria-label="业务域与系统入口"><div class="atlas-aside-head"><span id="atlas-kicker">选择业务域</span><button id="atlas-fold" aria-expanded="true" aria-label="收起导航列表">−</button></div><div id="atlas-list"></div><p id="atlas-status" role="status">拖动 360° 环游 · 滚轮缩放<br>悬停大洲轻轻上浮，点建筑开始探索。</p></aside><div class="atlas-walk" hidden aria-label="人物移动"><button data-atlas-walk="w" aria-label="向前走">↑</button><button data-atlas-walk="a" aria-label="向左走">←</button><button data-atlas-walk="s" aria-label="向后走">↓</button><button data-atlas-walk="d" aria-label="向右走">→</button></div><button id="atlas-talk" hidden>和 NPC 聊聊 · E</button><p class="atlas-footnote">系统方案导览 · 从业务问题走向执行流程</p></div>`);
document.body.insertAdjacentHTML('beforeend',`<dialog id="system-dialog" aria-labelledby="system-dialog-title"><button class="atlas-dialog-close" aria-label="关闭系统对话">×</button><div class="system-dialog-grid"><aside class="system-npc"><div id="system-portrait"></div><small id="system-npc-name"></small><p id="system-npc-line"></p><span class="system-badge">系统向导</span></aside><section class="system-conversation"><span class="atlas-overline" id="system-domain"></span><h2 id="system-dialog-title"></h2><ol class="system-steps" aria-label="问答进度"><li>模块</li><li>场景</li><li>对象与频率</li><li>老板问题</li></ol><div id="system-answer"></div><p id="system-error" role="status"></p><footer class="system-dialog-actions"><button id="system-prev">← 上一步</button><span id="system-page"></span><button id="system-next" class="atlas-primary">继续 →</button></footer></section></div></dialog><dialog id="atlas-directory" aria-labelledby="atlas-directory-title"><button class="atlas-dialog-close" aria-label="关闭系统图鉴">×</button><span class="atlas-overline">MY FIELD NOTES / 系统图鉴</span><h2 id="atlas-directory-title">把业务问题，串成一张地图。</h2><p>选择系统，走进对应大洲。标记表示已读完导览。</p><div id="atlas-directory-list"></div></dialog>`);
const modal=$('#system-dialog'),directory=$('#atlas-directory');
function count(){ $('#atlas-catalog b').textContent=read.size+' / 13';}
function openDomain(id,sid=null){if(!domains.some(d=>d.id===id&&!d.locked))return;if(window.atlasWorld){atlasWorld.enter(id,sid)}else{domain=domains.find(d=>d.id===id);syncMode();if(sid)openSystem(sid)}}
function visit(id){const s=systems.find(s=>s.id===id);if(!s)return;directory.close();if(domain?.id!==s.domainId||!window.atlasWorld)openDomain(domains.find(d=>d.systems.includes(s)).id,id);else atlasWorld.travel(id)}
function syncMode(){ $('#atlas-title').textContent=domain?domain.nick+' · '+domain.name:'五大洲，一个自动化世界。';$('#atlas-subtitle').textContent=domain?`${domain.systems.length} 套系统 · 走近建筑，与系统向导聊聊。`:'4 个业务域 · 13 套系统 · 42 个子模块';$('#atlas-back').hidden=!domain;$('#atlas-box').hidden=!!domain;$('.atlas-walk').hidden=!domain;$('#atlas-talk').hidden=true;$('#atlas-kicker').textContent=domain?'本洲系统':'选择业务域';
 $('#atlas-list').innerHTML=domain?domain.systems.map(s=>`<button class="atlas-system-card" data-visit="${s.id}">${portrait(s)}<span><b>${esc(s.short)}</b><small>${esc(s.npc)} · ${s.modules.length} 个子模块${read.has(s.id)?' · 已探索':''}</small></span><i>↗</i></button>`).join(''):domains.map(d=>`<button class="atlas-domain-card" data-enter="${d.id}" ${d.locked?'disabled aria-disabled="true"':''} style="--domain-color:${d.color}"><span class="atlas-number">${d.i!==undefined?d.i+1:domains.indexOf(d)+1}</span><span><b>${esc(d.name)}</b><small>${d.nick} · ${d.locked?'待开发':d.systems.length+' 套系统'}</small></span><i>${d.locked?'◌':'↗'}</i></button>`).join('');
 $('#atlas-status').innerHTML=domain?'点建筑让斌哥带伙伴前往 · WASD 行走<br>拖动旋转视角 · 走近后按 E 对话':'拖动 360° 环游 · 滚轮缩放<br>悬停大洲轻轻上浮，点建筑开始探索。';count();}
function renderDirectory(){ $('#atlas-directory-list').innerHTML=domains.map(d=>`<section class="directory-domain"><h3><span style="background:${d.color}"></span>${esc(d.name)}${d.locked?' · 待开发':''}</h3>${d.systems.map(s=>`<button data-visit="${s.id}">${portrait(s)}<span><b>${esc(s.short)}</b><small>${s.modules.length} 模块 · ${esc(s.npc)}</small></span><i>${read.has(s.id)?'✓':'↗'}</i></button>`).join('')}${d.locked?'<p>留一片空白，给下一种可能。</p>':''}</section>`).join('');}
function openSystem(id){const s=systems.find(s=>s.id===id);if(!s)return;currentSystem=s;selected=new Set(s.modules.map(m=>m.id));step=0;origin=document.activeElement;$('#system-portrait').innerHTML=portrait(s);$('#system-npc-name').textContent=s.npc;$('#system-domain').textContent=domains.find(d=>d.systems.includes(s)).name;$('#system-dialog-title').textContent=s.name;$('#system-npc-line').textContent=['先把问题讲清楚，再一起找办法。','把每一步做好，结果会慢慢靠近。','不确定的地方，我们先核对依据。','耐心听完需求，才能做出有用的东西。'][systems.indexOf(s)%4];renderStep();modal.showModal();}
function renderStep(){const s=currentSystem,mods=s.modules.filter(m=>selected.has(m.id));$('#system-error').textContent='';$('.system-conversation').scrollTop=0;$('.system-steps').querySelectorAll('li').forEach((el,i)=>{el.classList.toggle('active',i===step);if(i===step)el.setAttribute('aria-current','step');else el.removeAttribute('aria-current')});$('#system-page').textContent=(step+1)+' / 4';$('#system-prev').hidden=step===0;$('#system-next').textContent=step===3?'记入图鉴 ✓':'继续 →';
 if(step===0){$('#system-answer').innerHTML=`<h3>系统子模块有哪些？</h3><p class="answer-intro">可以多选您关心的模块。后面的场景和问题会随选择展开。</p><fieldset class="module-options"><legend class="sr-only">选择想了解的子模块</legend>${s.modules.map(m=>`<label><input type="checkbox" value="${m.id}" ${selected.has(m.id)?'checked':''}><span><b>${esc(m.name)}</b><small>${esc(m.scene)}</small></span></label>`).join('')}</fieldset><div class="module-selection"><button id="modules-all">全选</button><button id="modules-none">清空</button><span>已选 <b id="module-count">${mods.length}</b> / ${s.modules.length}</span></div>`;}
 else {const titles=['','覆盖哪些业务场景？','适合谁？发生频率？','老板关心的核心问题是什么？'];$('#system-answer').innerHTML=`<h3>${titles[step]}</h3><p class="answer-intro">${s.npc}说：按您选择的 ${mods.length} 个模块，我们逐一来看。</p><div class="answer-cards">${mods.map(m=>`<article><h4>${esc(m.name)}</h4>${step===1?`<p>${esc(m.scene)}</p>`:step===2?(()=>{const a=m.audienceFrequency.split('；');return `<dl><dt>适合谁</dt><dd>${esc(a[0])}</dd><dt>发生频率</dt><dd>${esc(a.slice(1).join('；')||'资料未单列')}</dd></dl>`})():`<p>${esc(m.pain)}</p><details><summary>看看全流程如何衔接</summary><ol>${m.flow.split('→').map(x=>`<li>${esc(x.trim())}</li>`).join('')}</ol></details>`}</article>`).join('')}</div>${step===3?`<button class="atlas-reference-link" data-reference-system="${s.id}">查看本系统代表案例与当前进度 ↗</button>`:''}${step===3?'<p class="system-source">内容依据：您提供的《AI自动化应用系统》表。此处展示系统设计；数据接入、自动执行与业务效果以实际项目验证为准。</p>':''}`;}
}
$('#system-answer').addEventListener('click',e=>{const b=e.target.closest('[data-reference-system]');if(b){modal.close();window.portfolioUI?.openSystem(b.dataset.referenceSystem,$('#atlas-talk'));}});
$('#system-answer').addEventListener('change',e=>{if(e.target.type!=='checkbox')return;e.target.checked?selected.add(e.target.value):selected.delete(e.target.value);$('#module-count').textContent=selected.size});
$('#system-answer').addEventListener('click',e=>{if(e.target.id==='modules-all'){selected=new Set(currentSystem.modules.map(m=>m.id));renderStep()}if(e.target.id==='modules-none'){selected.clear();renderStep()}});
$('#system-prev').onclick=()=>{if(step>0){step--;renderStep()}};
$('#system-next').onclick=()=>{if(!selected.size){$('#system-error').textContent='先选一个想了解的子模块，再继续。';return}if(step<3){step++;renderStep()}else{read.add(currentSystem.id);try{localStorage.setItem('dabin-atlas-v22',JSON.stringify([...read]))}catch{storageOK=false}modal.close();syncMode();$('#atlas-status').textContent=currentSystem.short+' 已记入图鉴。'+(storageOK?'可以继续走向另一座建筑。':'当前浏览器未允许保存，关闭页面后可能丢失记录。')}};
for(const d of[modal,directory]){d.querySelector('.atlas-dialog-close').onclick=()=>d.close();d.addEventListener('close',()=>{if(origin?.isConnected)origin.focus({preventScroll:true})});}
$('#atlas-catalog').onclick=()=>{origin=document.activeElement;renderDirectory();directory.showModal()};
$('#atlas-back').onclick=()=>{if(window.atlasWorld)atlasWorld.overview();else{domain=null;syncMode()}};
$('#atlas-turn').onclick=()=>{const state=window.atlasWorld?.state();if(state){const index=(Math.round(state.longitude/(Math.PI/2))+1)%4;atlasWorld.rotateTo(domains[(index+4)%4].id)}};
$('#atlas-box').onclick=()=>{boxMode=!boxMode;$('#atlas-box').setAttribute('aria-pressed',String(boxMode));window.atlasWorld?.setBox(boxMode);$('#atlas-status').textContent=boxMode?'在星球上拖出选择框，选中后点击提示进入。第五洲不可选。':'普通拖拽已恢复为 360° 旋转。'};
$('#atlas-fold').onclick=()=>{const folded=$('.atlas-aside').classList.toggle('folded');$('#atlas-fold').setAttribute('aria-expanded',String(!folded));$('#atlas-fold').textContent=folded?'+':'−'};
$('.atlas-hud').addEventListener('click',e=>{const d=e.target.closest('[data-enter]'),s=e.target.closest('[data-visit]');if(d&&!d.disabled)openDomain(d.dataset.enter);if(s)visit(s.dataset.visit)});
$('.atlas-hud').addEventListener('pointerover',e=>{const d=e.target.closest('[data-enter]');if(d&&!d.disabled)window.atlasWorld?.hover(d.dataset.enter)});$('.atlas-hud').addEventListener('pointerout',e=>{if(e.target.closest('[data-enter]'))window.atlasWorld?.hover(null)});
directory.addEventListener('click',e=>{const s=e.target.closest('[data-visit]');if(s)visit(s.dataset.visit)});
document.querySelectorAll('[data-atlas-walk]').forEach(b=>{b.onpointerdown=e=>{b.setPointerCapture(e.pointerId);window.atlasWorld?.key(b.dataset.atlasWalk,true)};b.onpointerup=b.onpointercancel=()=>window.atlasWorld?.key(b.dataset.atlasWalk,false)});
window.addEventListener('atlasmode',e=>{domain=domains.find(d=>d.id===e.detail.domain)||null;syncMode()});
window.addEventListener('atlasblocked',()=>{$('#atlas-status').textContent='这条路线暂时不通，请先走到中央广场再选择建筑。'});
window.addEventListener('atlastravel',e=>{const s=systems.find(s=>s.id===e.detail.id);$('#atlas-talk').hidden=true;$('#atlas-status').textContent='斌哥与芽芽、阿零正前往「'+s.short+'」。'});
window.addEventListener('atlasarrive',e=>{const s=systems.find(s=>s.id===e.detail.id);if(!s)return;$('#atlas-status').textContent='已来到「'+s.short+'」，'+s.npc+'在等您。';$('#atlas-talk').hidden=false;$('#atlas-talk').textContent='和'+s.npc+'聊聊 · E';$('#atlas-talk').onclick=()=>openSystem(s.id);openSystem(s.id)});
window.addEventListener('atlasbox',e=>{const ds=domains.filter(d=>e.detail.ids.includes(d.id));$('#atlas-status').innerHTML=ds.length?`已框选：${ds.map(d=>`<button class="atlas-box-result" data-enter="${d.id}">${esc(d.name)} ↗</button>`).join('')}`:'没有框到可探索的大洲。请先旋转到正面再框选。'});
// Keep the real portfolio casebook below; add a distinct, data-driven business map entry.
const map=$('#world-index');if(map&&!map.classList.contains('pf-intro')){map.innerHTML=`<div class="field-intro"><div><span class="field-kicker">BUSINESS ATLAS / 五大洲业务地图</span><h2>从一个业务问题，<br><span>走进一套系统。</span></h2></div><p>四个业务域，十三套系统。<br>与每座建筑的向导聊聊，<br>选择模块，了解场景与适用对象。</p></div><div class="atlas-ground-nav">${domains.map(d=>`<button data-ground-domain="${d.id}" ${d.locked?'disabled':''}><small>${d.nick}</small><b>${esc(d.name)}</b><span>${d.locked?'待开发':d.systems.length+' 套系统 ↗'}</span></button>`).join('')}</div>`;map.addEventListener('click',e=>{const b=e.target.closest('[data-ground-domain]');if(b&&!b.disabled){$('#explore-world').click();openDomain(b.dataset.groundDomain)}});}
$('.hero-cta').href='#world-index';$('.hero-cta').firstChild.textContent='探索五大洲 ';$('.scene-help>span').textContent='360° 旋转 · 选择业务域';$('#planet').setAttribute('aria-label','五大洲3D业务地图。拖动可360度旋转；业务域和系统也可从旁边导航进入。');
if(innerWidth<701){$('.atlas-aside').classList.add('folded');$('#atlas-fold').setAttribute('aria-expanded','false');$('#atlas-fold').textContent='+';}
window.atlasUI={openSystem,visit,state:()=>({domain:domain?.id,system:currentSystem?.id,step,selected:[...selected],read:[...read]})};syncMode();
if(!window.atlasWorld){document.body.classList.add('atlas-read-mode');$('#explore-world').hidden=false;$('.scene-fallback').hidden=false;$('.scene-fallback').innerHTML='<strong>业务地图 · 阅读模式</strong><p>当前环境未启用3D渲染，仍可从系统图鉴阅读完整模块与问答。</p>';}
})();
