/* V15: Yaya four-legged trot atlas; V14 robot leg mesh stride; V13: original-design alpha sprites, 2.5D billboards in the world depth buffer. */
window.createCompanionRenderer=(gl,host)=>{
 'use strict';const canvas=host||document.querySelector('#planet');
 const compile=(type,source)=>{const s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s};
 const pg=gl.createProgram();gl.attachShader(pg,compile(gl.VERTEX_SHADER,'attribute vec2 p;uniform mat4 vp;uniform vec3 center,right,up;uniform vec2 dimensions;uniform vec4 frame;uniform float running,kind,phase;varying vec2 uv; void main(){  vec2 q=p;float x=p.x*512.,y=(1.-p.y)*512.;  if(running>.5){   float side=x<264.?-1.:1.;float step=sin(phase+side*1.5707963);   float hip=mix(416.,383.,kind);   float leg=smoothstep(hip,mix(470.,450.,kind),y);   float region=mix(smoothstep(130.,155.,x)*(1.-smoothstep(349.,370.,x)),1.,kind);   float lift=max(0.,step);   if(kind<.5){    q.y+=leg*region*(lift*23.-max(0.,-step)*6.)/512.;    q.x+=leg*region*(step*26.+side*lift*6.)/512.;   }else{    float w=smoothstep(385.,455.,y);    q.x+=w*step*24./512.;    q.y+=w*(lift*27.-max(0.,-step)*10.)/512.;   }   /* Counter-swing arms while face and chest stay stable. */   float arm=smoothstep(279.,367.,y)*(1.-smoothstep(398.,419.,y));   float edge=(1.-smoothstep(190.,220.,x))+smoothstep(326.,355.,x);   q.y-=kind*arm*edge*step*19./512.;   q.x+=kind*arm*edge*side*lift*8./512.;  }  vec3 w=center+right*(q.x-.5)*dimensions.x+up*q.y*dimensions.y;  gl_Position=vp*vec4(w,1.);uv=frame.xy+p*frame.zw; }'));
 gl.attachShader(pg,compile(gl.FRAGMENT_SHADER,'precision mediump float;uniform sampler2D atlas;varying vec2 uv;void main(){vec4 c=texture2D(atlas,uv);if(c.a<.025)discard;gl_FragColor=c;}'));gl.linkProgram(pg);if(!gl.getProgramParameter(pg,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(pg));
 const U={};for(const n of ['vp','center','right','up','dimensions','frame','atlas','running','kind','phase'])U[n]=gl.getUniformLocation(pg,n);const A=gl.getAttribLocation(pg,'p');
 const vertices=[];for(let y=0;y<72;y++)for(let x=0;x<64;x++){const a=x/64,b=y/72,c=(x+1)/64,d=(y+1)/72;vertices.push(a,b,c,b,a,d,a,d,c,b,c,d)}const buffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(vertices),gl.STATIC_DRAW);
 const textures=[];let ready=false;
 Promise.all(['yaya','aling','yaya-trot'].map((name,i)=>new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>{const tex=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,tex);gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL,true);gl.pixelStorei(gl.UNPACK_PREMULTIPLY_ALPHA_WEBGL,false);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,im);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);textures[i]=tex;resolve()};im.onerror=()=>reject(Error('原设定角色素材加载失败'));im.src='assets/'+(i===2?'yaya-trot-v15.png':name+'-sprites-v13.png')}))).then(()=>{ready=true;canvas.dataset.companions='ready';canvas.dataset.crewStyle='original-illustration';if(canvas.id==='planet')window.dispatchEvent(new Event('companionsready'))}).catch(e=>{canvas.dataset.companions='error';if(canvas.id==='planet')window.dispatchEvent(new CustomEvent('companionerror',{detail:e.message}))});
 function start(vp){gl.useProgram(pg);gl.uniformMatrix4fv(U.vp,false,new Float32Array(vp));gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.enableVertexAttribArray(A);gl.vertexAttribPointer(A,2,gl.FLOAT,false,0,0);gl.enable(gl.BLEND);gl.blendFuncSeparate(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA,gl.ONE,gl.ONE_MINUS_SRC_ALPHA);gl.depthMask(false);gl.activeTexture(gl.TEXTURE0);gl.uniform1i(U.atlas,0);}
 function draw(i,center,right,up,size,state,time){gl.uniform1f(U.running,state==='run'&&i===1?1:0);gl.uniform1f(U.kind,i);gl.uniform1f(U.phase,time*9);let frame=state==='run'?0:state==='think'?3:state==='jump'?4:state==='sleep'?5:0;const col=frame%3,row=Math.floor(frame/3),pad=.0005;gl.uniform4fv(U.frame,[col/3+pad,1-(row+1)/2+pad,1/3-pad*2,1/2-pad*2]);gl.uniform3fv(U.center,center);gl.uniform3fv(U.right,right);gl.uniform3fv(U.up,up);gl.uniform2fv(U.dimensions,[size,size]);if(i===0&&state==='run'){
  const step=Math.floor(time*7)%4,col=step%2,row=Math.floor(step/2);
  gl.uniform4fv(U.frame,[col*.5+.002,1-(row+1)*.5+.002,.496,.496]);
  const dx=[0,.022,-.02,.006][step],dy=step>1?-.05:0;
  gl.uniform3fv(U.center,center.map((v,j)=>v+size*(right[j]*dx+up[j]*dy)));
  gl.bindTexture(gl.TEXTURE_2D,textures[2]);
 }else gl.bindTexture(gl.TEXTURE_2D,textures[i]);gl.drawArrays(gl.TRIANGLES,0,vertices.length/2);}
 function finish(){gl.depthMask(true);gl.disable(gl.BLEND);}
 const unit=a=>{const d=Math.hypot(...a)||1;return a.map(v=>v/d)};
 return{free({width,height,time,actors}){if(!ready)return false;start([2/width,0,0,0,0,2/height,0,0,0,0,-.001,0,-1,-1,0,1]);actors.forEach((a,i)=>{const tilt=a.state==='run'&&i===1?Math.sin(time*7+i)*.045:0,c=Math.cos(tilt),s=Math.sin(tilt),breath=a.state==='sleep'?1+Math.sin(time*1.8)*.015:1;draw(i,[a.x,height-a.y,0],[(i===0&&a.state==='run'&&a.heading<0?-1:1)*c,(i===0&&a.state==='run'&&a.heading<0?-1:1)*s,0],[-s,c,0],a.size*1.8*breath,a.state,time+i*.18)});finish();return true;},render({vp,yaw,time,moving,fox,robot,size=1.2}){if(!ready)return;start(vp);const right=unit([vp[0],vp[4],vp[8]]),up=unit([vp[1],vp[5],vp[9]]);[fox,robot].forEach((p,i)=>{if(!p)return;const c=Math.cos(yaw),s=Math.sin(yaw),position=[c*p[0]+s*p[2],p[1],-s*p[0]+c*p[2]];const radial=unit(position),outward=unit(up.map((v,j)=>v));draw(i,position,right,outward,size,moving?'run':'idle',time+i*.18)});finish();return true;}};
};
