(()=>{'use strict';
const systems=JSON.parse(document.querySelector('#portfolio-data').textContent),dialog=document.querySelector('#pf-system-dialog'),content=dialog.querySelector('#pf-dialog-content');let opener=null;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

function references(s){return (s.references||[]).map(r=>`<section class="pf-reference-detail"><div class="pf-kicker">${esc(r.eyebrow)}</div><h3>${esc(r.title)}</h3><span class="pf-badge reference">${esc(r.status)}</span><div class="pf-reference-watch"><video controls playsinline preload="metadata" poster="assets/jev-v36/${r.id}.jpg" aria-label="${esc(r.title)}：外部参考片段"><source src="assets/jev-v36/${r.id}.mp4" type="video/mp4"></video><div><p><b>AI风向标 · 原视频节选</b></p><p>原片 ${esc(r.stamp)}，裁去节目包装，保留案例画面与原声。</p><p>原作者介绍的场景与数据，仅用作方案参考，不代表本人项目成果。</p><a href="https://www.douyin.com/video/7688725366814428458" target="_blank" rel="noopener noreferrer">查看抖音原视频 ↗</a></div></div><h4>业务问题</h4><p>${esc(r.problem)}</p><h4>${r.id==='laya'?'已整理的部署方案':'拟落地的业务流程'}</h4><p>${esc(r.design)}</p><div class="pf-flow">${r.steps.map(x=>`<span>${esc(x)}</span>`).join('')}</div><h4>${r.id==='laya'?'已有产物':'预期产物'}</h4><ul>${r.outputs.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><div class="pf-boundary"><h4>案例边界与当前状态</h4><p>${esc(r.boundary)}</p></div><div class="pf-guide-links"><a href="downloads/laya-windows-v35.html" target="_blank" rel="noopener">Windows 部署教程 ↗</a><a href="downloads/laya-macos-v35.html" target="_blank" rel="noopener">macOS 部署教程 ↗</a><a href="https://github.com/NandhaKishorM/laya" target="_blank" rel="noopener noreferrer">Laya 作者仓库 ↗</a></div></section>`).join('')}


function gongbei(s){const c=s.gongbeiCase;if(!c)return '';return `<section class="pf-gongbei-detail"><div class="pf-kicker">AI 协作开发 / 企业流程工具替代实践</div><h3>${esc(c.title)}</h3><p class="pf-gongbei-subtitle">${esc(c.subtitle)}</p><span class="pf-badge supported">${esc(c.status)}</span><figure class="pf-gongbei-screen pf-gongbei-film"><video controls playsinline muted preload="metadata" poster="${esc(c.poster)}" aria-label="${c.videoDuration}秒功倍复刻开发过程极速回顾"><source src="${esc(c.video)}" type="video/mp4"></video><figcaption>${c.videoDuration} 秒极速回顾 · 240—900 倍速 · 原录屏无音轨</figcaption><p class="pf-gongbei-video-note">AI 协作与原平台对照的过程记录，局部人员信息与浏览器地址已遮挡，其余画面保持清晰。</p></figure><p><a href="${esc(c.image)}" target="_blank" rel="noopener">查看脱敏界面大图 ↗</a></p><a class="pf-gongbei-live" href="${esc(c.url)}" target="_blank" rel="noopener noreferrer">打开在线演示 ↗</a><h4>业务问题</h4><p>${esc(c.problem)}</p><h4>我如何把需求变成可体验的结果</h4><p>${esc(c.work)}</p><p>${esc(c.role)}</p><div class="pf-flow">${c.steps.map(x=>`<span>${esc(x)}</span>`).join('')}</div><h4>已形成的产物</h4><ul>${c.outputs.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><h4>对老板的实际价值</h4><p>${esc(c.value)}</p><div class="pf-boundary"><h4>当前交付边界</h4><p>${esc(c.boundary)}</p><p>${esc(c.timing)}</p></div><p class="pf-dlg-source">材料依据：${esc(c.source)}</p><p class="pf-gongbei-related">对应商品全生命周期的上新协作、库存与采购系统的采购协同。案例覆盖流程承载与展示层，不代表这些系统的全部 AI 模块已实现。</p></section>`}

function preview(c){const m=c.preview;if(!m)return '';return `<figure class="pf-artifact"><div class="pf-artifact-frame ${m.type}">${m.type==='video'?`<video controls playsinline preload="metadata" ${m.original?'muted':''} poster="${esc(m.poster)}" aria-label="${esc(c.title)} · ${esc(m.label)}"><source src="${esc(m.full||m.src)}" type="video/mp4"></video>`:`<a href="${esc(m.full||m.src)}" target="_blank" rel="noopener" aria-label="打开${esc(c.title)}成果大图"><img src="${esc(m.full||m.src)}" alt="${esc(m.caption)}" width="1280" height="800"></a>`}</div><figcaption><strong>${esc(m.label)}</strong><p>${esc(m.caption)}</p><div class="pf-artifact-links">${m.type==='image'?`<a href="${esc(m.full||m.src)}" target="_blank" rel="noopener">查看清晰大图 ↗</a>`:''}${m.download?`<a href="${esc(m.download)}" download>下载匿名汇总 CSV ↓</a>`:''}${m.original?`<a href="${esc(m.original)}" target="_blank" rel="noopener">观看原速有声版 ↗</a>`:''}</div></figcaption></figure>`}
function story(c){return `<section class="pf-dlg-case"><div class="pf-kicker">CASE NOTES / ${esc(c.status)}</div><h3>${esc(c.title)}</h3><p class="pf-case-summary">${esc(c.lead||'')}</p>${c.methodologyCase?window.portfolioMethodsV46.factory():""}${preview(c)}<h4>业务问题</h4><p>${esc(c.problem)}</p><h4>${c.status.includes('待开发')?'方案设计':'实践与材料'}</h4><p>${esc(c.work)}</p><div class="pf-flow">${c.steps.map(x=>`<span>${esc(x)}</span>`).join('')}</div><h4>${c.status.includes('待开发')?'拟形成的交付物':'现有产物'}</h4><ul>${c.outputs.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><h4>老板关心的价值</h4><p>${esc(c.value)}</p><div class="pf-case-measure"><b>后续如何验证</b><p>${esc(c.metric)}</p><small>以上为评估口径，不是已取得的提效数据。</small></div><div class="pf-boundary"><h4>当前阶段与覆盖边界</h4><p>${esc(c.boundary)}</p></div><p class="pf-dlg-source">材料依据：${esc(c.source)}</p>${c.mediaLink?`<a href="${esc(c.mediaLink)}" data-close-system>观看已有作品与流程讲解 ↓</a>`:''}</section>`}
function openSystem(id,from,index=0){document.querySelector("#gongbei-timelapse")?.pause();dialog.querySelectorAll('video').forEach(v=>v.pause());const s=systems.find(x=>x.id===id);if(!s)return;if(from)opener=from;const cases=s.representativeCases;index=Math.max(0,Math.min(cases.length-1,Number(index)||0));const c=cases[index];
content.innerHTML=`<div class="pf-kicker">${esc(s.nick)} / ${esc(s.domainName)} / ${s.id.slice(1)}</div><h2 id="pf-dialog-title">${esc(s.name)}</h2><p class="pf-dlg-intro">${esc(s.description)}</p><div class="pf-dlg-meta"><div><span>适合谁</span>${esc(s.audience)}</div><div><span>发生频率</span>${esc(s.frequency)}</div></div><div class="pf-case-selector" role="group" aria-label="选择代表案例">${cases.map((x,i)=>`<button data-select-case="${i}" data-case-system="${id}" aria-pressed="${i===index}"><small>CASE ${String(i+1).padStart(2,'0')} · ${esc(x.status)}</small><span>${esc(x.title)}</span></button>`).join('')}</div>${c.kind==='gongbei'?gongbei(s):c.kind==='reference'?references({...s,references:s.references.filter(r=>r.id===c.refId)}):story(c)}<h3>系统模块与业务场景</h3><p>以下为系统规划；案例仅覆盖上述已说明的部分。展开模块查看业务场景。</p>${s.modules.map(m=>`<details><summary>${esc(m.name)}</summary><div class="pf-module-detail"><p><b>覆盖场景：</b>${esc(m.scene)}</p><p><b>适合谁 / 频率：</b>${esc(m.audienceFrequency)}</p><p><b>老板关心：</b>${esc(m.pain)}</p><p><b>规划流程：</b>${esc(m.flow)}</p>${m.id==="m13"?window.portfolioMethodsV46.branch(m):""}</div></details>`).join('')}<div class="pf-dialog-actions"><button data-world-system="${s.id}" data-world-domain="${s.domainId}">去 ${esc(s.nick)}，和 ${esc(s.npc)} 聊聊 ↗</button>${s.id==='s04'?'<a href="#screening-room" data-close-system>观看营销成片 ↓</a>':''}</div>`;
if(!dialog.open)dialog.showModal();dialog.scrollTop=0;dialog.querySelector('.pf-dialog-close').focus({preventScroll:true});}
document.querySelectorAll('.portfolio-v32 [data-system]').forEach(b=>b.addEventListener('click',e=>{openSystem(b.dataset.system,b,b.dataset.caseIndex);if(e.target.closest('.pf-preview')){const frame=content.querySelector('.pf-artifact,.pf-gongbei-screen,.pf-reference-watch');frame?.scrollIntoView({block:'center'});const v=frame?.querySelector('video');if(v){v.muted=true;v.play().catch(()=>{});}}}));
dialog.querySelector('.pf-dialog-close').addEventListener('click',()=>dialog.close());
dialog.addEventListener('click',e=>{const select=e.target.closest('[data-select-case]');if(select){openSystem(select.dataset.caseSystem,null,select.dataset.selectCase);content.querySelector(`[data-select-case="${select.dataset.selectCase}"]`).focus({preventScroll:true});return;}const go=e.target.closest('[data-world-system]');if(go){dialog.close();window.atlasWorld?.enter(go.dataset.worldDomain,go.dataset.worldSystem);return;}if(e.target.closest('[data-close-system]'))dialog.close();if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
dialog.addEventListener('close',()=>{dialog.querySelectorAll('video').forEach(v=>v.pause());if(opener?.isConnected)opener.focus({preventScroll:true})});
window.portfolioUI={openSystem};
document.addEventListener('play',e=>{if(e.target.matches?.('video'))document.querySelectorAll('video').forEach(v=>{if(v!==e.target)v.pause()})},true);
const nav=[...document.querySelectorAll('.pf-domain-nav a')],sections=[...document.querySelectorAll('.pf-domain')];
let scheduled=false;function highlight(){scheduled=false;const current=[...sections].reverse().find(s=>s.getBoundingClientRect().top<=180)||null;nav.forEach(a=>{const active=current&&a.hash==='#'+current.id;a.classList.toggle('is-active',!!active);if(active)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current')})}window.addEventListener('scroll',()=>{if(!scheduled){scheduled=true;requestAnimationFrame(highlight)}},{passive:true});highlight();
})();
